### ISSUE TITLE
tests.edn location + optional?

### ISSUE THREAD

**Issue by martinklepsch** [lambdaisland/kaocha#1]
I always try to keep a projects root directory as clean as possible in order to make it easy to get an overview. For that it would be nice if tests.edn could be placed elsewhere as well — maybe at the root of the classpath (e.g. in `resources`)?

Also I'm fairly happy with the "zero-config" `#kaocha {}`, in this case creating the tests.edn file seems unnecessary?

**Comment by plexus** [comment]
You can point at an alternative location with --config-file. It's quite
deliberate though that tests.edn lives at the top level, next to deps.edn.

You're right though that it should be optional if you're fine with the
defaults. Kaocha used to do that, but that disappeared when I did a big
internal rewrite. It's on my list to bring that back.
