### ISSUE TITLE
Potential kaocha --watch regression from versions 367 to 389

### ISSUE THREAD

**Issue by teodorlu** [lambdaisland/kaocha#100]
Hello!

First, thanks for a great project. I've really been enjoying working with kaocha. It's fast, and it does what I need. Great work!

Onto the boring stuff. I have a project where `bin/kaocha --watch` works for kaocha version 0.0-367, but not with version 0.0-389 or later (I've tested 0-0.418 and a few in between). See the [example repo][1] for steps to reproduce and relevant source.

I might be doing something wrong, or it might actually be a regression.

Thanks again, and have a nice day!

[1]: https://github.com/teodorlu/potential-kaocha-regression-from-367-to-389/tree/fdf947fc791b56e19f9183e3ccee31720d73cfa9

**Comment by teodorlu** [comment]
Since I expect the `--watch` switch to be commonly used, I'm a little surprised that just I am reporting this. I suspect it might have something to do with my configuration specifically.

Are there any others that can `--watch` work after version 367?

**Comment by teodorlu** [comment]
Since `kaocha.watch` uses `hawk {:mvn/version "0.2.11"}`, I figured I'd try to find out if this is an upstream problem. My conclusion: hawk seems to work.

Running this on my system,

```clojure
(ns scratch.watch-stuff
  (:require [hawk.core :as hawk]))

;; Question: Does hawk even work on my system?

(defn watch-handler [ctx e]
  (prn :event e)
  (prn :context ctx))

(hawk/watch! [{:paths ["/home/teodorlu/workspace/watching"]
               :handler #'watch-handler}])
```
, then in a terminal

```
teodorlu@L470 ~/workspace/watching % ls
teodorlu@L470 ~/workspace/watching % touch file
teodorlu@L470 ~/workspace/watching % rm file
teodorlu@L470 ~/workspace/watching % echo 999 > nums
teodorlu@L470 ~/workspace/watching % touch file
teodorlu@L470 ~/workspace/watching % echo 99 >> file
teodorlu@L470 ~/workspace/watching % echo "more stuff " >> file
teodorlu@L470 ~/workspace/watching % rm file
```

produces this REPL output

```clojure
:event {:kind :create, :file #object[java.io.File 0x39e007b "/home/teodorlu/workspace/watching/file"]}
:context nil
:event {:kind :modify, :file #object[java.io.File 0x31b27500 "/home/teodorlu/workspace/watching/file"]}
:context nil
:event {:kind :modify, :file #object[java.io.File 0x69a20426 "/home/teodorlu/workspace/watching/file"]}
:context nil
:event {:kind :modify, :file #object[java.io.File 0x36290bcf "/home/teodorlu/workspace/watching/file"]}
:context nil
:event {:kind :delete, :file #object[java.io.File 0x7015ce33 "/home/teodorlu/workspace/watching/file"]}
:context nil
```

**Comment by plexus** [comment]
Hi @teodorlu, it's entirely possible there's a regression. I'll try to look into it this week.

**Comment by teodorlu** [comment]
Sounds good! Let me know if you need any details.

**Comment by plexus** [comment]
You didn't have a `tests.edn`, which was triggering an issue that has been fixed on master for a while now. I'm cutting a new release so people can more easily upgrade.

**Comment by teodorlu** [comment]
Confirmed -- `tests.edn` present fixed the old release, and the new release did not require `tests.edn`.

Thanks!
