### ISSUE TITLE
notify-send needs timeout

### ISSUE THREAD

**Issue by devn** [lambdaisland/kaocha#102]
On Ubuntu 19.04, Kaocha notify-send notifications do not go away until they are explicitly acknowledged/clicked. They pile up on successive runs, and then you need to click as many times as you had a failing or passing test in order to get them all off of your screen.

I experienced this while working with a coworker, so I am unable to test myself, but I wonder if utilizing notify-send's timeout flag would alleviate this issue.

**Comment by plexus** [comment]
From the man page

```
       -t, --expire-time=TIME
              The duration, in milliseconds, for the notification to appear on screen.  (Ubuntu's Notify OSD and GNOME Shell both ignore this parameter.)
```

So not sure that will fix this.
