### ISSUE TITLE
Getting --help

### ISSUE THREAD

**Issue by AndreaCrotti** [lambdaisland/kaocha#105]
Not using options like `--print-test-plan` every day I forget them every time I need them, and it's always a bit of a pain to look them up again.

I wonder why `--help` doesn't work, would be very useful to see all the possible options you can pass that way, and it's more or less standard.

**Comment by plexus** [comment]
This is a limitation of clojure cli. You can use --test-help.

**Comment by AndreaCrotti** [comment]
Ok thanks I can close this then
