### ISSUE TITLE
How to implement shared tests?

### ISSUE THREAD

**Issue by darkleaf** [lambdaisland/kaocha#109]
How to implement shared tests?

First example. I have a protocol and its tests. I'm wanting to run tests for given protocol implementations.

Second example. I have several systems (integrant or component) and application tests. I'm wanting to run tests for each system.

**Comment by plexus** [comment]
Hi @darkleaf,

For open ended support questions like this you are better off on the forum (https://clojureverse.org/c/projects/kaocha). This isn't really a Kaocha concern though, I would maybe look into `clojure.test/are`, or just use regular clojure.

``` clojure
(defn protocol-tests [impl]
  (is (= ... (foo impl))
  (is (= ... (bar impl)))

(deftest impl1-test
  (protocol-tests (Impl1.)))

(deftest impl2-test
  (protocol-tests (Impl2.)))
```
