### ISSUE TITLE
Idea: Dynamic runtime test skipping

### ISSUE THREAD

**Issue by glenjamin** [lambdaisland/kaocha#110]
An approach I've used in a few other languages is to have a sub-suite of tests check for the presense or availability of an external dependency, and then skip any related tests if that's not found.

The usual use-case is that I might have some test which talk to the database, and if I'm not running the database locally I'd rather skip all of the tests (and have them marked as skipped), than attempt to run them and get a bunch of possibly misleading errors.

In such a system, I'd also usually configure the skip logic to never kick in if it detects that it's running in CI.

Is this something that can be done with the current plugin architecture? I'd imagine most of the time i'd want to put that sort of logic in a test fixture.

**Comment by plexus** [comment]
Hi @glenjamin,

Sorry for the very slow response! You caught me at a bad time, I'm slowly catching up on my inbox :)

What you describe is a perfect use case for a plugin. Have a look at the [version filter plugin](https://github.com/lambdaisland/kaocha/blob/master/src/kaocha/plugin/version_filter.clj), this lets you skip specific tests based on the Clojure or Java version. 

I would recommend a similar approach, add some metadata to the tests, then use a plugin to mark them as skipped.

``` clojure
(deftest ^:skip-on-ci my-test ,,,)
```

``` clojure
(ns glenjamin.skip-on-ci
  (:require [kaocha.plugin :refer [defplugin]]
            [kaocha.testable :as testable]))

(defplugin glenjamin/skip-on-ci
  (pre-test [testable test-plan]
    (if (and (= (System/getenv "CI") "true")
             (:skip-on-ci (::testable/meta testable)))
      (assoc testable ::testable/skip true)
      testable)))
```

``` shellsession
$ bin/kaocha --plugin glenjamin/skip-on-ci
```
