### ISSUE TITLE
Default to the dev profile?

### ISSUE THREAD

**Issue by AndreaCrotti** [lambdaisland/kaocha#118]
When I started using Kaocha I followed the suggestion to add all the dependencies into the "kaocha" profile.e

This is a good suggestion, but I wonder if it should be the default.
I stopped using the kaocha profile, just because it makes it a bit less convenient for everyone to have kaocha always available (in the Repl for example)
It's still possible of course with the right parameters passed to Leiningen for example, but imho it doesn't really harm to have it in the dev profile rather than the Kaocha profile.

Any thoughts?

**Comment by alysbrooks** [comment]
I agree that the dev profile is a better default. I think we should retain the description of making it a separate profile for people who either:

- Rarely or never use Kaocha in the REPL
- Only use Kaocha for a specific purpose, e.g., if they usually use the default test runner but use Kaocha for test profiling.

**Comment by plexus** [comment]
I think that makes sense, with Clojure CLI I tend to stick kaocha in the `:test` alias, which I make sure to include when starting a REPL. People should have Kaocha available when working on the REPL by default, so I think for Leiningen recommending the `:dev` profile is a good idea.

**Comment by alysbrooks** [comment]
Since we're agreed, I can update the docs.

**Comment by alysbrooks** [comment]
Thanks! I updated our docs to recommend the `:dev` profile, so I think this is addressed.
