### ISSUE TITLE
Invalid test namespace silently fails

### ISSUE THREAD

**Issue by tomafro** [lambdaisland/kaocha#135]
Running a test suite where one of the tests has an error in the namespace silently ignores this invalid test. I'd expect it instead to show an error and fail the test suite.

I've created a repository with a minimal case to reproduce here: https://github.com/tomafro/kaocha-syntax-error-not-failing

The `README.md` tries to explain the problem, reproduced below.

In the master branch of this project, running the tests produces the following output (as expected):

    ❯ clojure -A:test
    [(.)]
    1 tests, 1 assertions, 0 failures.

Changing to the branch `test-with-broken-syntax-declaration` (where a bracket has been removed from the `ns` declaration) gives the following instead:

    ❯ clojure -A:test
    []
    0 tests, 0 assertions, 0 failures.

I would expect that instead kaocha would complain that it couldn't load the test file, and return with an error status.

You can compare the two branches here: https://github.com/tomafro/kaocha-syntax-error-not-failing/compare/test-with-broken-syntax-declaration?expand=1

Please let me know if I can help any further to get to the bottom of this.

**Comment by plexus** [comment]
I'm looking into this. Thanks a lot for setting up a repro, that's super helpful! :+1:

**Comment by plexus** [comment]
Turns out this is actually caused by tools.namespace, we use that to scan for namespaces in a directory, and it silently ignores files where it's unable to read an ns form.

Luckily we already run a fork of tools.namespace, so I think we can patch this.

**Comment by tomafro** [comment]
Thanks so much for the quick fix and explanation.
