### ISSUE TITLE
Support Clojure Expectations For Colourised Output

### ISSUE THREAD

**Issue by dharrigan** [lambdaisland/kaocha#136]
Hi,

There is an excellent library called Clojure Expectations that can be found [here](https://github.com/clojure-expectations/clojure-test). It describes itself as `A clojure.test-compatible version of the classic Expectations testing library.` and is actively maintained (unlike the classic library). This library is also 100% compatible with the Clojure Test namespace.

Unfortunately, at the moment, if there are test failures, there is no pretty output from Kaocha like there is with the standard Clojure Test reporting. The output on test failure from Clojure Test is nice colouring of the information to highlight test differences.

Using Expectations, the output is not colourised by Kaocha.

Here is an example from Kaocha using the debug output of a test failure showing a `deftest` output:

```
{:type :fail, :file "foo_test.clj", :line 64, :expected (= true false), :actual (not (= true false)), :message nil, :kaocha/testable #:kaocha.testable{:id :txi.robin.patterns.foo-test/foobar, :type :kaocha.type/var}}
```

and here is one using the Expecations output showing `defexpect` output:

```
{:type :fail, :file "foo_test.clj", :line 61, :expected (=? true false), :actual (not (=? true false)), :message "", :kaocha/testable #:kaocha.testable{:id :txi.robin.patterns.foo-test/foo, :type :kaocha.type/var}}
```

I hope that helps. Let me know if you require further information.

-=david=-

**Comment by plexus** [comment]
The problem is that kaocha doesn't know what `=?` means. Is that an Expectations thing?

This is where the pretty printing of `=` failures is implemented: https://github.com/lambdaisland/kaocha/blob/master/src/kaocha/report.clj#L241-L267

You could add something similar for `=?`
