### ISSUE TITLE
Add a flag to disable dynamically adding :test-paths

### ISSUE THREAD

**Issue by robert-stuttaford** [lambdaisland/kaocha#144]
...  and let people manage their own classpath.

@plexus what extra context would you like me to provide in this issue? :)

**Comment by plexus** [comment]
All good like this :) Should be fixed in `{lambdaisland/kaocha {:mvn/version "1.0.632"}}`, but still needs to be documented.

``` clojure
#kaocha/v1 
{:tests
 [{:test-paths [...]
   :kaocha.testable/skip-add-classpath? true}]}
```

**Comment by robert-stuttaford** [comment]
It works! Yay! Thank you for the assistance, @plexus !
