### ISSUE TITLE
File watching fails on MacOS Big Sur beta

### ISSUE THREAD

**Issue by rgm** [lambdaisland/kaocha#151]
There's an issue in JNA that's biting Figwheel too for users on macOS v10.16 / v11 / Big Sur or whatever we're calling it (ie. the new version for Sept 2020 being beta tested right now). The annual increase in security-related lockdowns has introduced a crasher into JNA, which kills barbary, which kills hawk, which kills `bin/kaocha --watch`.

https://github.com/bhauman/figwheel-main/issues/253

The low-friction temp fix we figured out for Figwheel while this is being sorted out is to tell hawk to start with a `:polling` watcher instead of a `:barbary` watcher. It kills battery life since it's no longer using native filesystem change events, but at least it keeps things working while it gets sorted out at the JNA level.

Is there a similar way to allow passing hawk options into kaocha, or, if not, a PR for the same being welcome? Might be a useful add beyond this one temp fix. I think it's in Figwheel to help cope with some Docker-related issues.

**Comment by alysbrooks** [comment]
@rgm Looks like this has been fixed? https://github.com/thheller/shadow-cljs/issues/767. Adding the ability to pass hawk options isn't a bad idea, so I may keep this issue open for that change.

**Comment by alysbrooks** [comment]
Oh, I figured out you can already pass options into Hawk: https://cljdoc.org/d/lambdaisland/kaocha/CURRENT/doc/7-watch-mode#configuring-the-watcher

**Comment by oxalorg** [comment]
Fixed in #268 and released in `v1.62.993`
