### ISSUE TITLE
Tests are passing with lein test but failing with lein kaocha

### ISSUE THREAD

**Issue by cksharma11** [lambdaisland/kaocha#154]
I'm facing an issue with Kaocha where my unit tests are passing with `lein test` but when I'm running `lein kaocha` some of the tests are failing.

I'm not sure but somehow the issue seems like : https://github.com/cloverage/cloverage/issues/300

**Comment by plexus** [comment]
You're going to have to be more specific @cksharma11 . What are the tests doing? How are they failing?

Ideally you should try to create a minimal project that reproduces the issue. If that's not feasible then at least provide as much information as possible. Maybe put your project.clj and affected test files in a gist so we can look at them?

Thanks!

**Comment by cksharma11** [comment]
@plexus Yes I agree. 
I'll try to create a small project for the same issue to reproduce.

for now what I can tell you is that, in the test we're mocking with mock-clj and those functions are not getting mocked actually 

for example : `(is (= 1 (mock/call-count hikari/some-fn-foo)))` is resulting in 0 calls instead of 1.

I know it's not very clear yet.
