### ISSUE TITLE
:focus-meta running only first match with namespaces meta

### ISSUE THREAD

**Issue by cksharma11** [lambdaisland/kaocha#155]
I have ns meta for multiple files and I have defined tests.edn file for running different id.

when I'm specifying :focus-meta which is present in multiple file it runs only the first match.

I've created a sample project to reproduce the same issue :
https://github.com/cksharma11/kaocha-issue-sample

**Comment by plexus** [comment]
Your example works as expected.

- You didn't specify `:ns-patterns`, and you have two test namespaces that don't end on `-test`, so these are ignored.
- the end result is that you have two test suites that both only run the `core-test`

```
➜ clj -A:kaocha:dev -m kaocha.runner --reporter kaocha.report/documentation
WARNING: No tests found with metadata key :foo. Ignoring --focus-meta :foo.
--- unit (clojure.test) ---------------------------
kaocha-issue-sample.core-test
  mock-private-test
  test-bar
    foo with mock
--- foo-test (clojure.test) ---------------------------
kaocha-issue-sample.core-test
  test-bar
    foo with mock
  mock-private-test

4 tests, 12 assertions, 0 failures.
```

If you add a more permissive `:ns-patterns` then you get this:

```
#kaocha/v1
{:tests [{:id          :unit
          :ns-patterns [".*"]}
         {:id          :foo-test
          :ns-patterns [".*"]
          :focus-meta  [:bar]}]}
```

**Comment by cksharma11** [comment]
@plexus Thanks for the explanation :)

Yes you are right I have tested it and it works.

I was trying to use kaocha in existing project (as the lein test was not so useful) which is big enough and was replacing `lein test :foo` via kaocha. And in the process what I thought is to use the same pattern with kaocha to run with namespace meta. which caused the problem that I was explaining before. 

After adding `:ns-pattern` it solved the current problem.

Thank you for the effort and time 👍
