### ISSUE TITLE
kaocha.plugin.alpha.spec-test-check ignores configuration from tests.edn

### ISSUE THREAD

**Issue by robhanlon22** [lambdaisland/kaocha#156]
https://github.com/lambdaisland/kaocha/blob/master/src/kaocha/plugin/alpha/spec_test_check.clj#L56

These lines should be modified not to only read from the CLI-supplied configuration for instrumentation and assertion checking—they should grab these values from `tests.edn` if they're available, because the values specified in `tests.edn` are quietly ignored. To use the configuration from `tests.edn`, one must manually set up a generative fdef check suite. Not a huge deal, but it's something I didn't notice until I was debugging some other test configuration and I saw that these configuration values were unexpectedly set to nil.

I can open a PR that does this when I have some time. Thanks for the great piece of software!

**Comment by plexus** [comment]
You're right, the config hook should check that it doesn't overwrite values that are already in the config with nil. A PR would be great! Thanks
