### ISSUE TITLE
Watch feature should ignore temporary files

### ISSUE THREAD

**Issue by emlyn** [lambdaisland/kaocha#16]
It would be good if there was a way to specify patterns of filenames to ignore from the watch feature (e.g. `.#*` files created by emacs) so that tests are not needlessly reevaluated every time a temporary file changes.

**Comment by danielcompton** [comment]
Would it be useful to be able to infer this from local and global gitignore settings? That seems like it would cover most of the kinds of files you'd want to ignore changes to. There might need to be a setting to turn this off and be more specific in very unusual cases, but I suspect drafting off of Git's settings here could be quite nice. Also not sure how/if you'd do this for other VCS's.

**Comment by plexus** [comment]
Thanks @emlyn and @danielcompton, these are really good suggestions. I'll see if I can add some kind of include/exclude mechanism.
