### ISSUE TITLE
Should ::stc/check-asserts? and ::stc/instrument? be specified at the test level?

### ISSUE THREAD

**Issue by robhanlon22** [lambdaisland/kaocha#160]
Right now, `::stc/opts` comes in as part of a test configuration:

https://github.com/lambdaisland/kaocha/blob/29ad4279b45310df5294fb9ee686aee5b71fee41/src/kaocha/plugin/alpha/spec_test_check.clj#L31

But the other options come in as part of the global configuration:

https://github.com/lambdaisland/kaocha/blob/29ad4279b45310df5294fb9ee686aee5b71fee41/src/kaocha/plugin/alpha/spec_test_check.clj#L56
https://github.com/lambdaisland/kaocha/blob/29ad4279b45310df5294fb9ee686aee5b71fee41/src/kaocha/plugin/alpha/spec_test_check.clj#L59

It would be more consistent to choose one or the other. Happy to do the work once a decision is made.

**Comment by plexus** [comment]
I guess that's what you get for this being a plugin and a test type at the same time. I've never been very happy about that.

I think the right answer is both, i.e. the implementation should look for them at the test type level, and the plugin should add them to the test based on the global config.

**Comment by robhanlon22** [comment]
Sounds good. I'll open a PR for this because I'm familiar with that area of the code.

**Comment by plexus** [comment]
:+1: thanks
