### ISSUE TITLE
Clarify how to use REPL from Leningen

### ISSUE THREAD

**Issue by alysbrooks** [lambdaisland/kaocha#166]
If you follow the installation setup, Kaocha isn't available from the Leiningen REPL because you're creating a separate profile. Instead of `lein repl`, you need to do `lein with-profile +kaocha repl`.

Alternatively, we could implement  #118. I'm listing this as a separate issue in case we want to keep the Kaocha profile around as an alternative option.

**Comment by plexus** [comment]
Let's go with #118 , people can still put it into its own profile if they like, but that way the default setup is a little more foolproof.

**Comment by alysbrooks** [comment]
Fixed by #170 ✨
