### ISSUE TITLE
Add explanation of defaults from README to Docs

### ISSUE THREAD

**Issue by alysbrooks** [lambdaisland/kaocha#167]
I tried Kaocha on my own project and after installation, I was unclear on whether configuration was necessary, recommended, or optional. We do [a great job clarifying this in the README](https://github.com/lambdaisland/kaocha#all-tools), but I missed the Quickstart section. I think we should explain it in the Configuration section of the docs as well.

**Comment by plexus** [comment]
Thanks for fixing this!
