### ISSUE TITLE
Watch mode improvements

### ISSUE THREAD

**Issue by plexus** [lambdaisland/kaocha#17]
There are several things regarding `--watch` mode that could be improved.

- [x]  A configurable include/exclude mechanism, seeded from `.gitignore` #16 
- [x]  Watch changes to `tests.edn` (related to 1., but also requires using a new test config)
- [x]  Drop `core.async`. It's the only place in the code where it's used, and a simple Java blocking queue would work just as well. This would help improve start up time.
- [x]  Don't build when a source namespace has load errors. Kaocha turns errors during the load step into test failures, so that one broken test ns doesn't stop the build from running, but errors in source namespaces should be treated as a broken precondition and fixed first.

**Comment by chadharrington** [comment]
An additional issue that we'd like to resolve:
If code changes in a dependent project that I am hacking on (via :local/root coordinates), I'd like the tests to re-run. I am not sure how to make that work, but lein-test-refresh does behave this way when using lein checkouts.

**Comment by plexus** [comment]
@chadharrington as a workaround you can add the extra directories you want to watch to `:source-paths` in `tests.edn`

**Comment by plexus** [comment]
All of the issues mentioned here have been addressed in #54, except adding an include mechanism (workaround: use `:source-paths`), and seeding from `.gitignore`, (see #55).
