### ISSUE TITLE
Watch ignore patterns do not apply to deleted files

### ISSUE THREAD

**Issue by russmatney** [lambdaisland/kaocha#178]
Much thanks for the work on kaocha - it's a great tool!

I am creating and deleting intermediary files in some of my tests, which is causing --watch to loop forever. I'd hoped to prevent this using the `:kaocha.watch/ignore` patterns, but the ignores do not apply to deleted files. I believe this is because of the `(file? f)` guard in `kaocha.watch/wait-and-rescan!` ([code here](https://github.com/lambdaisland/kaocha/blob/1732bf51e1f37cffd0018c1dad0f9c1b2bd0fe4b/src/kaocha/watch.clj#L92)), which returns false if the passed `f` does not exist (as is always the case for a deleted file).

Removing the guard works for my case, but causes the kaocha lib tests to hang - I've read the watch tests, but haven't made progress addressing them, and am not sure removing the guard is the right step here anyway. It might make more sense to ignore at the hawk/watch level, perhaps in `kaocha.watch/watch!`.

Not sure when I'll have time to approach a PR for this, but wanted to report it - happy to take a shot if a better solution comes to mind.

**Comment by humorless** [comment]
Hello @russmatney 

Using the newest version of kaocha, I could not reproduce this issue on my computer, which is a Mac M1. I have tried to use beholder and hawk, but none of them can reproduce the issue. 

```
(defmethod watch! :hawk [{:keys [q watch-paths opts]}]
  (hawk/watch! opts
               [{:paths   watch-paths
                 :handler (fn [ctx event]
                            (when (= (:kind event) :modify)
                              (qput q (:file event))))}]))

(defmethod watch! :beholder [{:keys [q watch-paths]}]
  (apply beholder/watch
         (fn [{:keys [type path]}]
           (when (contains? #{:modify :create} type)
             (qput q path)))
         (map str watch-paths)))
```

From just reading the code, it seems that only create or modify event will trigger the watch. 

Can you reproduce this issue with the newest version of kaocha?

**Comment by russmatney** [comment]
Hi @humorless - thanks for looking into this! It's been quite a while, and I'm pretty far from the context on this. I'm glad you can't reproduce the issue, it's likely fixed, so feel free to close this! If I run into anything new I'll follow up then.
