### ISSUE TITLE
Error when passing --focus with multiple test ids

### ISSUE THREAD

**Issue by AndreaCrotti** [lambdaisland/kaocha#179]
With multiple test ids, currently passing `--focus` actually goes through all of them.
That's unlikely to be what you actually want and is just confusing, kaocha could just throw an error explaining that you need to pass the test-id as well.

**Comment by plexus** [comment]
It seems like we are talking past each other here, from what you said on Slack I understood that you wanted `--focus` without an argument to be an error, but that is already the case:

```
Missing required argument for "--focus SYM"
```

After reading this issue a few times and looking at your PR I see now that you're addressing something else, the fact that kaocha needs to scan the full test plan to find what to focus on. This is sometimes undesirable, but there's no easy solution for this.

It seems you want to make it impossible for people to use `--focus` without also specifying the test-suite, that's not desirable. You may want to `bin/kaocha --focus test-from-one-suite --focus test-from-other-suite`. You also shouldn't have to specify the test suite, that's never been a requirement and we're not going to change that.

**Comment by AndreaCrotti** [comment]
Yeah ok understood, I can probably close this then.
