### ISSUE TITLE
Boot support

### ISSUE THREAD

**Issue by plexus** [lambdaisland/kaocha#19]
I'd like to add Boot support soon, so all three major Clojure dependency/build tools are supported. This should be fairly straightforward as Kaocha has an easily consumable top level API. The biggest challenge will be to handle command line options.

Boot's `deftask` macro has a declarative syntax for specifying command line options, but Kaocha determines which command line arguments it recognizes at runtime, because plugins can add extra command line options. E.g. if you run `bin/kaocha --plugin cloverage --help` you'll see a much longer list than when you just run `bin/kaocha`.

The process is roughly like this

- Run `tools.cli/parse-opts` using the built-in list of recognized flags/options
- Look for any `--config-file` or `--plugin` arguments
- Load the given config-file (or `./tests.edn`)
- Load all plugins specified in the config file or on the command line
- Run the `cli-options` hook of any plugin that implements it, this yields the final list (in tools.cli format) of all recognized arguments
- Run `tools.cli/parse-opts` again

I'm really not sure if something similar will be possible in Boot. If it is it would probably mean not using `deftask`, but instead using lower level APIs / creative metaprogramming.

An alternative would be to "encode" additional options, e.g.

```
boot kaocha --plugin foo --config-file bar --extra-opts '--plugin-opt-1 --plugin-opt-2'
```

But perhaps then the more general approach would be to allow specifying additional configuration keys as a clojure map. Well behaved plugins provide both CLI options and `tests.edn` config keys, so this should allow you to do all the same things.

```
boot kaocha --extra-config '{:my.plugin/foo 123}'
```

**Comment by martinklepsch** [comment]
I think it's realistic to assume that most invocations will eventually end up in `build.boot` where you can pass regular data to tasks.

Maybe for CLI experimentation it would be useful to still expose something so user can just provide a few args like `'--plugin-opt-1 --plugin-opt-2'`

But outside of that just have a `config` option that takes a map. If the config passed to the task replaces a separate `tests.edn` file maybe the right thing is just having a `tests-edn` option. This way the format is identical and documentation doesn't require adjustments based on build tool choice.

**Comment by plexus** [comment]
Implemented in https://github.com/lambdaisland/kaocha-boot
