### ISSUE TITLE
watch-test doesn't seem to actually be testing the behavior

### ISSUE THREAD

**Issue by alysbrooks** [lambdaisland/kaocha#190]
I was trying to write a similar test for the `.gitignore` feature, and I wasn't sure it was actually testing so I tried commenting things out to get it to fail, without success. It seems like the same is true for the test I based it off of `kaocha.watch-test/watch-test`

It looks like this is using `is` with a value as its first argument:

```clojure
(is (str/replace "[(F)]\n\nFAIL in foo.bar-test/xxx-test (bar_test.clj:1)\nExpected:\n  :xxx\nActual:\n  -:xxx +:yyy\n1 tests, 1 assertions, 1 failures.\n\n[watch] Reloading #{foo.bar-test}\n[watch] Re-running failed tests #{:foo.bar-test/xxx-test}\n[(F)]\n\nFAIL in foo.bar-test/xxx-test (bar_test.clj:1)\nExpected:\n  :xxx\nActual:\n  -:xxx +:zzz\n1 tests, 1 assertions, 1 failures.\n\n[watch] watching stopped.\n"
                     "foo"
                     prefix)
        @out-str))
```

When I change it to the following, it fails:

```clojure
(is (= (str/replace "[(F)]\n\nFAIL in foo.bar-test/xxx-test (bar_test.clj:1)\nExpected:\n  :xxx\nActual:\n  -:xxx +:yyy\n1 tests, 1 assertions, 1 failures.\n\n[watch] Reloading #{foo.bar-test}\n[watch] Re-running failed tests #{:foo.bar-test/xxx-test}\n[(F)]\n\nFAIL in foo.bar-test/xxx-test (bar_test.clj:1)\nExpected:\n  :xxx\nActual:\n  -:xxx +:zzz\n1 tests, 1 assertions, 1 failures.\n\n[watch] watching stopped.\n"
                     "foo"
                     prefix)
        @out-str)))
```

Additionally, commenting out some forms in the middle of the test doesn't appear to change the result.

**Comment by plexus** [comment]
Yup, good find, that test is not testing anything. Apparently I wrote it two years ago on the morning of my birthday, I guess I wasn't very awake yet...

**Comment by plexus** [comment]
No need dragging a useless test around. If it's not immediately obvious how to fix it then I think it's better if we just delete it, or at least give it a `^:kaocha/pending`

**Comment by dharrigan** [comment]
What would you like to do? (I'm in that area right now - remove it, or mark it as pending).

**Comment by plexus** [comment]
if it looks fixable then mark it as pending, if it's dead weight then remove it.

**Comment by alysbrooks** [comment]
I spent some time investigating this and every part of the test seems to be working except for the watcher picking up on the change. This includes the watcher finding the correct paths, the watched file being modified, and later output being included in `out-str`. The problem seems to be in hawk (or the configuration/our usage of hawk) but I cannot figure out what it is.
