### ISSUE TITLE
Clojure.test/run-tests replacement?

### ISSUE THREAD

**Issue by leppaott** [lambdaisland/kaocha#216]
Is there a way to call directly koacha as in clojure.test/run-tests and clojure.test/run-all-tests? We'd like to run koacha from a clojure container not from a command line.

**Comment by leppaott** [comment]
Found (k/run...)

**Comment by leppaott** [comment]
`In :test-paths, no such file or directory: test`

I'd like to run (k/run 'namespace.test) that is already included. Now it tries to load from a file.

Basically like this "in-buffer eval":
`(kaocha.repl/run
  (deftest my-test
    ,,,))`

**Comment by leppaott** [comment]
Ok right run recognizes *ns*. So:
`(clojure.test/run-tests 'namespace.test)
=>
(koacha/run (ns namespace.test) {:tests [] :kaocha/test-paths [] )

Hmm still tries to load that test directory and I don't want another config file...

**Comment by plexus** [comment]
Kaocha has to be able to find your tests on the filesystem, it simply won't work otherwise. If they are not in the default location you have to tell Kaocha where they are.

**Comment by leppaott** [comment]
Right seems so. Would be great if following worked in repl:
`(require 'namespace.tests)
 (k/run 'namespace.tests)`

And no test-paths should need to be defined in this use case.
