### ISSUE TITLE
kaocha.repl/run and run-all should catch :kaocha/early-exit

### ISSUE THREAD

**Issue by plexus** [lambdaisland/kaocha#231]
When running through the REPL there is no handler for these exceptions, causing them to bubble up. These exceptions are internal and should never bubble out of end-user APIs.

**Comment by alysbrooks** [comment]
You can reproduce this error by passing a nonexistent test ID to `kaocha.repl/run`.

**Comment by alysbrooks** [comment]
Fixed by #265.
