### ISSUE TITLE
Randomize seed not read from config

### ISSUE THREAD

**Issue by smitjh** [lambdaisland/kaocha#232]
Hi everyone, 

Just a small bug - the [documentation](https://cljdoc.org/d/lambdaisland/kaocha/1.0.861/doc/3-configuration) indicates that the randomization seed can be set with the keyword :kaocha.plugin.randomize/seed in the tests.edn file but the code only considers the command line flag:

https://github.com/lambdaisland/kaocha/blob/58d7870e65b925de5ddf029eb95b699d4fe77a78/src/kaocha/plugin/randomize.clj#L36-L39

I'm using the following simple fix: 

`seed       (or (get-in config [:kaocha/cli-options :seed])
                         (:kaocha.plugin.randomize/seed config))`

Not sure if it's worth a PR but I can create one if required :-)

Thanks for the great software!

**Comment by plexus** [comment]
The config still takes precedence

https://github.com/lambdaisland/kaocha/blob/58d7870e65b925de5ddf029eb95b699d4fe77a78/src/kaocha/plugin/randomize.clj#L44

**Comment by smitjh** [comment]
You know what I was debugging the seed for something else and completely missed that. Sorry for the bother!

**Comment by plexus** [comment]
No worries! This code is a bit convoluted because we had to get the priorities straight between cli arg, config, and default value. I'll close this now. Do report it if you see anything else that looks like a bug!
