### ISSUE TITLE
plugin-names with dots are normalized, but shouldn't

### ISSUE THREAD

**Issue by thumbnail** [lambdaisland/kaocha#235]
According to this comment, plugins that contain a period, shouldn't get the `kaocha.plugin`-prefix.
https://github.com/lambdaisland/kaocha/blob/58d7870e65b925de5ddf029eb95b699d4fe77a78/src/kaocha/plugin.clj#L69-L75

Although in a REPL session showed:

```clj
(normalize-name :test)
=> :kaocha.plugin/test
(normalize-name :my/test)
=> :my/test
(normalize-name :my.test)
=> :kaocha.plugin/my.test
```

It's likely because the arguments need to be switched around here:
https://github.com/lambdaisland/kaocha/blob/58d7870e65b925de5ddf029eb95b699d4fe77a78/src/kaocha/plugin.clj#L69-L75

Happy to provide a patch :)

**Comment by plexus** [comment]
Yes, please!
