### ISSUE TITLE
capture-output not capturing logs

### ISSUE THREAD

**Issue by AndreaCrotti** [lambdaisland/kaocha#237]
I noticed in some internal projects that even if `--capture-output` is turned on, all the logs are still printed out to stdout, even if the printlns are captured as expected.

I haven't been able to reproduce that issue in one of my other OSS projects, but we are just using clojure.tools.logging, and from what I could see in the capture-output code, it should just capture all the stdout/stderr, which is where the log must end up anyway.

So I'm a bit confused about how it can happen, any idea maybe?
I'll try to reproduce it in another project in the meanwhile, but would be good to know if someone else had the same issue.

**Comment by alysbrooks** [comment]
That is strange. We use the same technique as `clojure.tools.logging/log-capture!`, so it should work. In theory, `*err*` and `*out*` could be rebound in your tests or the code it calls, but if you were doing that, I'm guessing you'd know?

**Comment by AndreaCrotti** [comment]
Mm no we haven't done anything really, apart from maybe *not* using logback (with the usual XML config), but configuring logging all in Clojure in user.clj, which I guess is related with the fact that it behaves differently.
I guess I can just add another plugin to make it work properly also for logging.

**Comment by alysbrooks** [comment]
@AndreaCrotti I don't think you should need another plugin for this to work, unless your logging configuration is unusual in some way. If there's something we could add to the capture-output plugin, let us know!

**Comment by alysbrooks** [comment]
I reproduced the issue in one of our repositories for a client that uses `ch.qos.logback.core.ConsoleAppender`. I think you're right about needing to use `setOut` / `setErr` .

**Comment by alysbrooks** [comment]
FYI @AndreaCrotti that we reopened this issue.

**Comment by alysbrooks** [comment]
I suppose we could try to move initializing capture to earlier in the Kaocha run process, but that would probably be awkward and might not even work.

**Comment by max-reify** [comment]
Ah, I didn't realize that kaocha already called `setOut`/`setErr`. If that's the case, this is more complicated than I thought and indeed it maybe a timing thing.
