### ISSUE TITLE
Weird require issue

### ISSUE THREAD

**Issue by AndreaCrotti** [lambdaisland/kaocha#239]
In a project, we have:
```clojure
(require [...
             [kaocha.repl :as kr]
             ...
```
in a `dev.clj` file, then in a `user.clj` file we have:

`(defn ... [] .. (require 'dev).. )`

This was all working fine until we bumped the version of Kaocha (to 1.0.861), and since we did we get a weird error like

`could not resolve symbol require`
I would be that it's related with https://github.com/lambdaisland/kaocha/blob/main/src/kaocha/repl.clj#L1

And the even stranger thing is that moving that `kaocha.repl` require at the end of the requires in dev.clj fixes the issue.
So somehow having two dynamic requires calling each other can fail, but not always.
Any idea about what's going on?

EDIT: the fact that it doesn't work when the require is near the top could be related to the fact that clojure.core is still not available at that point, and then it is.
I think in any case that require at the top of kaocha.repl is potentially a problem.

**Comment by alysbrooks** [comment]
Thank you for the report! Using `require` in this way is an unusual approach, so it's possible it doesn't work in all scenarios.

>the fact that it doesn't work when the require is near the top could be related to the fact that clojure.core is still not available at that point, and then it is.

it looks like `ns` expands to `clojure.core/require` not `require`, so it's possible that prior to calling `ns` in a file, `clojure.core` hasn't been brought in.

**Comment by alysbrooks** [comment]
@AndreaCrotti You can try #240 using something like this in `deps.edn`:

{lambdaisland/kaocha {:git/url "https://github.com/lambdaisland/kaocha.git"
                                                      :sha "437db7e32ca55cbf4fb006b6d6f1576cbedd39c4"}}

**Comment by AndreaCrotti** [comment]
Ok I just tried it and it works with that change, thanks @alysbrooks
