### ISSUE TITLE
Make the quickstart easier to find

### ISSUE THREAD

**Issue by alysbrooks** [lambdaisland/kaocha#241]
Mitesh, Felipe, and I were noting that it's easy to miss that we have a quick start. To find the quick start you have to scroll a lot because it's beneath a list of projects, the definition of Kaocha, a section about supporting Lambda Island and the table of contents (while not being listed in the table of contents).
This is a quick fix but an important one.

**Comment by plexus** [comment]
I've been placing the section about supporting lambda island towards the
bottom on more recent projects, that would be an easy one to start with.

**Comment by alysbrooks** [comment]
#243 is merged, so closing.
