### ISSUE TITLE
Kaocha not interpreting correctly `:as-alias` from latest Clojure Alpha

### ISSUE THREAD

**Issue by Heliosmaster** [lambdaisland/kaocha#250]
This is largely do tue lack of support of it in `clojure.tools.namespace` (or its fork in case of Kaocha)

**Comment by alysbrooks** [comment]
Thanks for letting us know. It sounds like once `clojure.tools.namespace` is updated, we can update our fork.

Does the issue come when using `:as-alias` in any project namespace you're testing with Kaocha or just a test namespace?

**Comment by Heliosmaster** [comment]
There is already a patch submitted: https://clojure.atlassian.net/browse/TNS-56 
But i've went ahead and opened a PR against our fork: lambdaisland/tools.namespace#1

**Comment by Heliosmaster** [comment]
Fixed in f35a8b39eaf2f82f4b0fdfb22f7077ebf0f23276
