### ISSUE TITLE
Warning when printing config

### ISSUE THREAD

**Issue by dpetran** [lambdaisland/kaocha#266]
I'm following along in the docs for setting up kaocha with tools.deps and it says:
> Try it out! Use bin/kaocha --print-config to see the resulting test configuration.

When I do that I get this warning:

`WARNING: Implicit use of clojure.main with options is deprecated, use -M`

and then it prints the config.

This is my `bin/kaocha` file:
```
#!/usr/bin/env sh
clojure -A:test -m kaocha.runner "$@"
```

What do I need to change to not get the warning?

**Comment by dpetran** [comment]
The command should be `clojure -M:test -m kaocha.runner "$@"`

**Comment by plexus** [comment]
Unfortunately the core team introduced some breaking changes, so using `-A:` here is no longer recommended, even though it works fine, but it does give you that warning. `-M` is indeed the new way to do it.

If you would like to send a PR to update the docs for this that would be really appreciated!

**Comment by stelcodes** [comment]
This already got fixed with #288
