### ISSUE TITLE
Watch mode not working with neovim

### ISSUE THREAD

**Issue by frankitox** [lambdaisland/kaocha#277]
Hi! I've been trying to use watch mode and encountered a little problem with the [beholder](https://github.com/nextjournal/beholder) library. When saving a file in vim I get (instead of the `:modify` event) two other events:

```
{:type :delete, :path #object[sun.nio.fs.UnixPath 0x20718f55 "src/main.clj"]}
{:type :create, :path #object[sun.nio.fs.UnixPath 0x352320a7 "src/main.clj"]}
```

The source code only reloads tests on `:modify`

https://github.com/lambdaisland/kaocha/blob/7ea063dcb0c43889e72e09f7f8a3f52e5773ee7a/src/kaocha/watch.clj#L275-L280

Is it possible to change it so that it also checks for `:create`?

**Comment by oxalorg** [comment]
Thanks @frankitox for reporting this! 

As a workaround we still support the older `hawk` reloading. You can use that by setting `:kaocha.watch/type :hawk` in the configuration.

I wonder why there is a delete and create event 🤔 Some questions to ask would be
- is this vim specific or wsl2 specific?
- does vim write to a tmp file and then rename the inode on every save? 🤔

**Comment by jlesquembre** [comment]
I was having the same issue, and I found that the reason it the (neo)vim `backupcopy` option. By default, the value is `auto` (which is equal to `no` for most cases)

In short, with `no` (neo)vim re-creates the file every time, while with `yes` the file is modified. `set backupcopy=yes` solves the issue.

But looks like kaocha has a different logic based on the filewatcher. With `hawk` the `backupcopy` option is irrelevant, tests are always executed after a change.

**Comment by oxalorg** [comment]
Thanks @jlesquembre for digging into this! 

The easiest fix would be to reload on file create events as well, but I am not sure if it will have any unintended side effects? It probably shouldn't.

**Comment by alysbrooks** [comment]
Thanks for reporting this issue! To other Vim and Neovim users, note that `backupcopy` is *not* the same as `backup`. Another confusing part: If you use Vim defaults, `backupcopy` is set to no, but it saves a swap file locally, which will trigger watch.

To sum up:

|   | `noswapfile`* | `swapfile` |
|--|--|--|
| `backupcopy=no`/`backupcopy=auto` |   :x: broken | :heavy_check_mark: works (default) |
|`backupcopy=yes` | :heavy_check_mark: works | :heavy_check_mark: works |

*Or if swap is in a tmp directory.

Swap files are annoying and I don't think most people set `backupcopy`, so there's probably more people in the upper left corner than you'd expect, unfortunately.

**Comment by frankitox** [comment]
Thank you guys for the context about when this is a problem in vim. I'm not sure just executing tests for both `:modify` and `:create` events is the best solution. Because I'm able to trigger both events saving the file using another text editor. The solutions I can think of are:

1. Just debounce for a couple of milliseconds test execution
2. Add a new watch config option, something like `:kaocha.watch.beholder.event-types` which defaults to `#{:modify :create}`

Let me know if it makes sense

**Comment by alysbrooks** [comment]
I'm disinclined to add a new configuration option. I also think Hawk, our previous watcher, picked up `:create` events.

**Comment by frankitox** [comment]
Oh, no worries. For me, Hawk runs tests twice, I'm guessing it triggers once for `:delete` and other for `:create`. Just wanted to state that this could be an issue to someone using beholder.

The change in #282 is working precisely as I wanted it. Thank you! 😄
