### ISSUE TITLE
Misleading warning when focussing on non-existing test

### ISSUE THREAD

**Issue by DerGuteMoritz** [lambdaisland/kaocha#289]
When focussing on a non-existing test (e.g. due to a typo or because the test in question got renamed in the meantime), kaocha currently produces this warning:

```
WARNING: No tests were found, make sure :test-paths and :ns-patterns are configured correctly in tests.edn.
```

This is a bit misleading as it makes users think something is wrong with the test setup altogether, sending them down an unrelated rabbit hole. I assume this warning is always emitted when no tests remain after applying all filters. Maybe this could be changed so that it is only emitted when the initial set of tests (i.e. before filtering) is empty? If it's empty only after filtering, a more precise warning could be emitted instead.

Tested with 1.65.1029.

**Comment by alysbrooks** [comment]
Good idea. The warning isn't meant to be describe every reason we could end up with no tests, but I think the solution you outlined makes sense.

**Comment by plexus** [comment]
I think it can stay but we need to fix the behavior, if we do find tests but they are for whatever reason marked as skipped, then you should not see this message. I'd rather have it say nothing and just run 0 tests than tell the user the wrong thing. As a next step we can add specific helper messages for other scenarios, e.g. filters too strict. But we need to be careful as this thing has shown, ergonomic features like these increase complexity, thus making it more likely for things to go wrong, thus defeating their purpose.
