### ISSUE TITLE
Unknown option --watch, what am I doing wrong?

### ISSUE THREAD

**Issue by magnars** [lambdaisland/kaocha#30]
I am getting "Unknown option" for `--watch`.

- Other options seem to work (I tried `--fail-fast` and `--print-config`)
- Watching works with `#kaocha/v1 {:watch? true}`
-  The `--no-watch` is also unknown.

I am using leiningen: 

```
:profiles {:kaocha {:dependencies [[lambdaisland/kaocha "0.0-367"]]}}
:aliases {"kaocha" ["with-profile" "+kaocha" "run" "-m" "kaocha.runner"]}
```

Executable:

```
#!/bin/bash

lein kaocha "$@"
```

Output:

```
> bin/kaocha --watch
Unknown option: "--watch"
USAGE:

bin/kaocha [OPTIONS]... [TEST-SUITE]...

  -c, --config-file FILE     tests.edn  Config file to read.
      --print-config                    Print out the fully merged and normalized config, then exit.
      --print-test-plan                 Load tests, build up a test plan, then print out the test plan and exit.
      --print-result                    Print the test result map as returned by the Kaocha API.
      --fail-fast                       Stop testing after the first failure.
      --[no-]color                      Enable/disable ANSI color codes in output. Defaults to true.
      --[no-]watch                      Watch filesystem for changes and re-run tests.
      --reporter SYMBOL                 Change the test reporter, can be specified multiple times.
      --plugin KEYWORD                  Load the given plugin.
      --version                         Print version information and quit.
      --help                            Display this help message.
  -H, --test-help                       Display this help message.
      --[no-]randomize                  Run test namespaces and vars in random order.
      --seed SEED                       Provide a seed to determine the random order of tests.
      --skip SYM                        Skip tests with this ID and their children.
      --focus SYM                       Only run this test, skip others.
      --skip-meta SYM                   Skip tests where this metadata key is truthy.
      --focus-meta SYM                  Only run tests where this metadata key is truthy.
      --[no-]capture-output             Capture output during tests.

Options may be repeated multiple times for a logical OR effect.
Error encountered performing task 'run' with profile(s): 'base,system,user,provided,dev,kaocha'
Suppressed exit
```

**Comment by plexus** [comment]
This is strange... My only guess is that perhaps something is pulling in an older version of `tools.cli`, the `--[no-]foo` syntax was only added some time in the last year. Try adding `[org.clojure/tools.cli "0.4.1"]` to your dependencies.

**Comment by magnars** [comment]
The same goes for other `--[no-]x` options. I tried `--color`, `--no-color` and `--no-randomize`.

**Comment by magnars** [comment]
Thanks, I'll check my `lein deps :tree` 👍

**Comment by magnars** [comment]
Yes, indeed. Our `com.datomic/datomic-pro` dependency pulled in `org.clojure/tools.cli "0.3.5"`. Thanks for the help. I'm not sure if there's much you can do in the docs to avoid getting issues like this.

**Comment by magnars** [comment]
Thanks for making Kaocha, by the way. I have been missing a good test runner for Clojure since I started using it. Your work is most appreciated. 👍

**Comment by plexus** [comment]
It's good that it's reported now so people can find the issue. If it comes up regularly we can try to put it in a FAQ, although from experience people will drop into Clojurians chat before reading the FAQ, so as long as we can quickly point them somewhere it's all good :)

**Comment by AndreaCrotti** [comment]
I think that maybe if it's a known issue it could also be caught in the code, to display a more clear error.

If it just said "check your tools.cli dependency version and ensure it's greater than x.y" I would have known easily how to fix it.
