### ISSUE TITLE
Watch mode ignores :skip-meta

### ISSUE THREAD

**Issue by hukka** [lambdaisland/kaocha#310]
When watch mode is started with a profile that has `:skip-meta` set in tests.edn, pressing `Enter` runs all the tests, without skipping anything.

**Comment by alysbrooks** [comment]
Hi @hukka, thanks for reporting this. I'm having trouble replicating the issue. Can you share a `tests.edn` (at least the part with profile that uses `:skip-meta`)? Also, can you share the version of Kaocha you're using?

**Comment by alysbrooks** [comment]
Ahh, I misunderstood. I thought you had it disabled in a test suite, not a profile. Thanks for the info!

**Comment by hukka** [comment]
I changed my deps to `lambdaisland/kaocha {:git/url "https://github.com/lambdaisland/kaocha" :git/sha "48ad996fe695d39f1d246f649d50a840  5dc9ade5"}`, and now I'm getting
```
Syntax error compiling at (kaocha/config.clj:230:4).
Unable to resolve symbol: config in this context
```

**Comment by hukka** [comment]
For what's it worth, using `git/sha "6bac06a47235930a84fc4167d475d2ed1f1ce7a2"` (the first commit of the PR) works!

**Comment by alysbrooks** [comment]
Oh yeah, `48ad996fe695d39f1d246f649d50a8405dc9ade5` is a related WIP commit that got pushed to the wrong branch by mistake.
