### ISSUE TITLE
Enable notifier auto timeout option for notifications

### ISSUE THREAD

**Issue by bryanluu** [lambdaisland/kaocha#311]
On some operating systems, the notification supplied by the notifier plugin is persistent, annoying and disruptive, because either it is poorly designed, or it doesn't fade away. In my case, I am using Ubuntu 22.04.1 LTS, and the default notification is fairly annoying when no timeout is specified.

It would be nice if kaocha included some default timeout setting for either Mac or Linux options. I think Mac has autoexpiring notifications, but for Linux you can specify a timeout like `notify-send -t $timeout-in-millis`. Ideally, this would also be something that is configurable.
https://github.com/lambdaisland/kaocha/blob/42d7eb03001900ceeaca3dae0c003d40a8f277f7/src/kaocha/plugin/notifier.clj#L41

**Comment by alysbrooks** [comment]
I believe we've talked about this before.The notify-send option [doesn't work on certain desktop shells](https://github.com/lambdaisland/kaocha/issues/102#issuecomment-541378438). I think it still makes sense to support for the places where it does work, however.

What kind of timeout do you think would be a reasonable default? I'd probably go with 5 or 10 seconds (probably after trying some out).

**Comment by bryanluu** [comment]
> I believe this has come up before (#102).The notify-send option [doesn't work on certain desktop shells](https://github.com/lambdaisland/kaocha/issues/102#issuecomment-541378438). I think it still makes sense to support for the places where it does work, however.
Interesting. Testing on my machine, that flag doesn't seem to have an effect either.

> What kind of timeout do you think would be a reasonable default? I'd probably go with 5 or 10 seconds (probably after trying some out).
5 seconds seems reasonable to me.

Another alternative solution to this, which would be a new feature/issue, is to have different output levels. For example, I don't really need to get a notification for successes. If there was an option to send notifications only on failures or errors, that would be more useful and hopefully less noisy.

**Comment by alysbrooks** [comment]
One option I forgot until I read the documentation is ` :kaocha.plugin.notifier/command`. I'm not sure that removes the need for greater configurability.

Also, it appears `terminal-notifier` (macOS) doesn't support adding a timeout. You can, however, remove an old notification. So we could simulate timeouts with `future` I suppose. `terminal-notifier` also can be configured so new notifications replace old ones.
