### ISSUE TITLE
notifier option `--no-notifications` not working as expected on Ubuntu

### ISSUE THREAD

**Issue by bryanluu** [lambdaisland/kaocha#313]
When `kaocha` is run with the `--no-notifications` option on Ubuntu (I'm using Ubuntu 22.04.1 LTS), I expected no notification windows or pop-ups of any kind, but while I don't get my usual system notification, I get a strange, out-of-place notification instead.

With notifications (using Ubuntu system notification):
![image](https://user-images.githubusercontent.com/5415113/190867700-b76ab3a7-acc8-444b-8842-be5d6bd0bc8f.png)

With `--no-notifications`:
![Screenshot from 2022-09-14 15-21-37](https://user-images.githubusercontent.com/5415113/190867718-a68e15db-c70f-4231-ab4c-59ecc6f6f570.png)
It also causes strange artifacts to appear, seemingly glitching out GNOME (look at the top left corner):
![Screenshot from 2022-09-14 08-40-53](https://user-images.githubusercontent.com/5415113/190867722-bcfae61d-7768-499f-81cb-229ad4aae243.png)

This is a minor issue as this new notification is much less disturbing than the default Ubuntu system notification, but it's still weird. I did notice that this is mentioned in [`send-tray-notification`](https://github.com/lambdaisland/kaocha/blob/42d7eb03001900ceeaca3dae0c003d40a8f277f7/src/kaocha/plugin/notifier.clj#L88-L101), which is called when no notifications are specified, so it uses Java's notification system. But I would like an option (can be somethihng other than `--no-notifications`) that suppresses all UI notifications and only shows results no the Terminal.

**Comment by plexus** [comment]
Seems there's a logic error in the plugin, where `--no-notifications` would trigger the same fallback handler as if no command line utility for triggering notifications was found, and this then falls back to Java desktop tray notifications (which do look weird and dated).

I've released a fix in

```
[lambdaisland/kaocha "1.70.1086"]
{lambdaisland/kaocha {:mvn/version "1.70.1086"}}
```
