### ISSUE TITLE
Make it possible to specify the profile when using kaocha.repl

### ISSUE THREAD

**Issue by plexus** [lambdaisland/kaocha#319]
Currently we look up the profile directly in `:kaocha/cli-options`, so there's no good way to specify it in scenarios where we're not running via `kaocha.runner`.

This is probably also an issue with `-X`, but that's less important since people using `-X` should migrate to `-m` if they need that.

For starters we can simply look for a `:profile` key in the `extra-config` and `kaocha.repl/config` and use that.

**Comment by alysbrooks** [comment]
Fixed in #315 

Available in: 
```clojure
[lambdaisland/kaocha "1.76.1230"]                 ;; deps.edn
{lambdaisland/kaocha {:mvn/version "1.76.1230"}}  ;; project.clj
```

Or if you want the very latest version (at time of writing): 
```clojure
[lambdaisland/kaocha "1.78.1249"]                 ;; deps.edn
{lambdaisland/kaocha {:mvn/version "1.78.1249"}}  ;; project.clj
```
