### ISSUE TITLE
"--plugin kaocha.plugin/profiling" does not run when "--watch" is used

### ISSUE THREAD

**Issue by realgenekim** [lambdaisland/kaocha#332]
I'm not sure if this is a documentation issue or a functionality issue:

Currently, `--plugin kaocha.plugin/profiling` does not work when using `--watch` — I was expecting this to work, hoping that I could find all the tests that need to be flagged with meta of :integration.  Instead, profiling information never appeared.  To make it run, I had to remove `--watch` from command line.

Clojurians Slack discussion with @plexus here: https://clojurians.slack.com/archives/CCY2V0U6A/p1668771964181979

PS: thank you @plexus and everyone else who has made kaocha so amazing — I use it in all my projects that I care about.  For me, the `--watch` with notifier functionality on macOS makes for a nearly sublime development experience, in combination of the REPL.

**Comment by alysbrooks** [comment]
Hi Gene! Thanks for the kind words!

I think we probably want these to work together. Looking at the code, we don't appear to be running the `post-summary` hook that the profiling plugin uses to print the summary.

**Comment by plexus** [comment]
It seems I chose fairly early on to run it from the specific entry point (`kaocha.runner`), rather than in the shared logic in `kaocha.api`

```clj
commit 8935d79609970e5b58089cd1f971832e9c6b4f2c
Author: Arne Brasseur <arne@arnebrasseur.net>
Date:   Mon Jul 16 10:53:43 2018 +0200

    Run post-summary from kaocha.runner, not from kaocha.api
    
    Post-summary is mostly intended for side effects, outputing extra stuff at the
    end of the run (like profiling results). It makes more sense not to run it when
    using the API, this also prevents noise in EDN outputs like --print-result.
```

I think this makes sense, letting specific entry points opt-in to this behavior. I think it would make sense to let `kaocha.repl` also handle `post-summary`. I'll make an issue for that.

**Comment by plexus** [comment]
Moving this to "Out of Scope" on the project board since we are already tracking #335

**Comment by alysbrooks** [comment]
Profiling now runs from `--watch`, released in:

```[lambdaisland/kaocha "1.83.1316"]
{lambdaisland/kaocha {:mvn/version "1.83.1316"}}```
