### ISSUE TITLE
Docs Introduction implies that kaocha is still in alpha status.

### ISSUE THREAD

**Issue by skylize** [lambdaisland/kaocha#333]
From https://cljdoc.org/d/lambdaisland/kaocha/1.71.1119/doc/1-introduction
> Currently Kaocha's versioning scheme is `0.0-${commit count}`, and releases are made often. As long as the version is at `0.0` Kaocha will be considered alpha, in other words: subject to change.

Seeing as the current version is 1.71.1119, this seems to be deceptively underselling the maturity and expected stability of the project for potential new users.

**Comment by alysbrooks** [comment]
Hi @skylize, yes, I think it's safe to say we're out of alpha. :) Thanks for the bug report!
