### ISSUE TITLE
Implement the post-summary hook in kaocha.watch

### ISSUE THREAD

**Issue by plexus** [lambdaisland/kaocha#335]
`Kaocha.watch` should handle post-summary, that way plugins like `:kaocha.plugin/profiling` that output additional statistics at the end of the run work together with `--watch`.

See #332

**Comment by alysbrooks** [comment]
Fixed and released in:

```
[lambdaisland/kaocha "1.83.1316"]
{lambdaisland/kaocha {:mvn/version "1.83.1316"}}
```
