### ISSUE TITLE
Fail fast if clojure version < 1.9

### ISSUE THREAD

**Issue by plexus** [lambdaisland/kaocha#37]
We need 1.9 because of spec, we should find some way to communicate that immediately to the user, rather than erroring out on some failed require statement.

Same for Kaocha-cljs, which relies on ClojureScript 1.10 (and thus Clojure 1.10).

**Comment by danielcompton** [comment]
Does the spec backport library work, or is the spec use more integral here?

**Comment by plexus** [comment]
I have no idea, I never tried it. Does it also implement the extra predicates like `qualified-keyword?`? Is it compatible with Orchestra and Expound?

If someone wants to explore this that would of course be great, but I am not particularly invested in pursuing pre 1.9 compatibility. Say we manage to be 1.8-compatible and start getting more users, then we'll likely be tied to 1.8 for years to come, as I'd like to avoid dropping existing users. So I'd rather draw the line at 1.9, and try to keep 1.9 compatibility for the foreseeable future. (at least until there are a few more major Clojure versions out, and there's a compelling reason to get onto newer features).

**Comment by danielcompton** [comment]
Limiting support to 1.9 seems like a pretty reasonable default at the moment anyway, so it's probably not worth looking at too closely.

**Comment by alysbrooks** [comment]
I briefly tried the spec-backport library, and it wasn't enough to avoid errors—we'd have to backport other new functionality from 1.9, like `boolean?`.

**Comment by plexus** [comment]
I wouldn't put any effort into pre 1.9 compatibility at this point. The last Clojure Survey shows that close to 90% of the community is on 1.9 or 1.10, and that number will only increase.

https://clojure.org/news/2020/02/20/state-of-clojure-2020

**Comment by alysbrooks** [comment]
Should be addressed by #177
