### ISSUE TITLE
Kaocha watch mode not reporting load errors

### ISSUE THREAD

**Issue by frenchy64** [lambdaisland/kaocha#370]
When there are 2 (or more) entries in `:kaocha/tests` and you activate the second one in watch mode, if reloading a file fails, the stacktrace is not printed.

Please find a full reproduction here: https://github.com/frenchy64/reprod-kaocha-watch-bug

**Comment by alysbrooks** [comment]
Thank you for the issue and issue reproduction repository! I left some comments on your PR.
