### ISSUE TITLE
Suggestion: While watching, re-run all tests on first SIGINT

### ISSUE THREAD

**Issue by magnars** [lambdaisland/kaocha#39]
Sometimes changes are not detected (a git rebase, changes in non-clj files). Sometimes Kaocha is waiting for a single test to turn green, but you would like to run all the tests.

My suggestion is a SIGINT (Ctrl-C) would make Kaocha go:

```
Re-running all tests. Interrupt a second time to quit.
```

Then wait for two seconds for a second SIGINT before running all the tests.

I'd be happy to contribute something like this if it sounds reasonable.

**Comment by plexus** [comment]
I can see the use case for this, but I really don't like doing anything besides exiting on `SIGINT`. A lot of Ruby tools do this and it leads to some frustrating behavior.

I was going to say we could use `SIGQUIT` instead (`Ctrl-\`) but apparently the JVM already uses that. (TIL it prints out a stack trace, pretty useful :) )

But how about `STDIN`? We're not doing anything yet with user input, we could in watch mode respond to a user pressing enter to re-run the tests.

**Comment by magnars** [comment]
I can see the frustration. `STDIN` sounds like a good idea.

**Comment by plexus** [comment]
See also #26

**Comment by danielcompton** [comment]
SIGHUP is commonly used for reloading config and could be a good choice except that there is no standard keyboard shortcut for it.
