### ISSUE TITLE
Please bump beholder version so --watch works when editing with neovim

### ISSUE THREAD

**Issue by davesann** [lambdaisland/kaocha#397]
``` com.nextjournal/beholder {:mvn/version "1.0.2"} ```

see https://github.com/nextjournal/clerk/pull/397
and https://github.com/gmethvin/directory-watcher/issues/88

**Comment by alysbrooks** [comment]
I think bumping Beholder makes sense, but I would like to delve into this issue a little more. Back in [April 2022](https://github.com/lambdaisland/kaocha/issues/277#issuecomment-1088260802), I looked into a similar issue. The problem seemed to be limited to when both `noswapfile` and either `backupcopy=no` or `backupcopy=auto`.

**Comment by alysbrooks** [comment]
@davesann, what's your setting for `swapfile`? Also, which version of Kaocha are you using?

**Comment by alysbrooks** [comment]
#398 is merged.

You can test it out by pointing to the git changeset:
```clojure

{lambdaisland/kaocha {:git/url "https://github.com/lambdaisland/kaocha"
                      :git/sha "34c9975c0a3565de2995c131b57147386297883d"}}
```

**Comment by davesann** [comment]
> I think bumping Beholder makes sense, but I would like to delve into this issue a little more. Back in [April 2022](https://github.com/lambdaisland/kaocha/issues/277#issuecomment-1088260802), I looked into a similar issue. The problem seemed to be limited to when both `noswapfile` and either `backupcopy=no` or `backupcopy=auto`.

with the previous beholder version, I can fix ths issue by setting backupcopy=yes - see https://github.com/gmethvin/directory-watcher/issues/88 for details

**Comment by davesann** [comment]
> #398 is merged.
> 
> You can test it out by pointing to the git changeset:
> 
> ```clojure
> {lambdaisland/kaocha {:git/url "https://github.com/lambdaisland/kaocha"
>                       :git/sha "34c9975c0a3565de2995c131b57147386297883d"}}
> ```

validated - resolved for neovim.

**Comment by davesann** [comment]
> @davesann, what's your setting for `swapfile`? Also, which version of Kaocha are you using?

swapfile is default.

**Comment by alysbrooks** [comment]
> swapfile is as per default - so on (I think)

That definitely used to be the case. I think if you run `:swapname`, it will tell you the name of the swap file (if it's in use) and presumably nothing if it's disabled.

**Comment by alysbrooks** [comment]
Fix is released!

```clojure
[lambdaisland/kaocha "1.78.1249"]
{lambdaisland/kaocha {:mvn/version "1.78.1249"}}
```
