### ISSUE TITLE
Run post-summary in kaocha.repl

### ISSUE THREAD

**Issue by alysbrooks** [lambdaisland/kaocha#399]
`kaocha.repl` doesn't run the `post-summary` hook, so plugins like the profiling plugin don't display. These could be a bit noisy, so perhaps it should be behavior you turn on? Related to #335.

**Comment by humorless** [comment]
Hi @alysbrooks , 

I am trying to understand this issue, but I am quite confused. 
```
src/kaocha/repl.clj
157:           (plugin/run-hook :kaocha.hooks/post-summary)
```

What do you mean that it doesn't run?

**Comment by alysbrooks** [comment]
@humorless Not sure. I'm wondering if I was thinking of another hook. It does indeed seem to run, but I'm having issues seeing the post-summary hook results actually appear in the REPL. It's probably an unrelated issue.
