### ISSUE TITLE
Suggestion: Run all tests if no tests match --focus-meta

### ISSUE THREAD

**Issue by magnars** [lambdaisland/kaocha#40]
I like to run all the tests in a terminal with `--watch`. Sometimes I'd like to focus on just one namespace or a few tests, while I work on them. Afterwards I go back to running all the tests again.

The way `--focus-meta` works now, I have to restart Kaocha twice to do this. How about running all the tests when there are no matching tests? It might have to be opt-in, or come with a warning, if you are concerned about confusion.

**Comment by plexus** [comment]
I've thought about this a bit, and I think it's a good idea. Better to do something useful (run all tests) than do nothing.

It should come with a warning or message though, maybe something like this.

```
No tests found with metadata :xxx, ignoring --focus-meta :xxx.
```

**Comment by plexus** [comment]
I'm ok with making this configurable, maybe something like this?

```
#kaocha/v1
{:kaocha/warnings
 {:focus-meta-not-found false
  ;;:deprecated-config-literal true
  ;;:test-path-does-not-exist true
  }}
```

**Comment by magnars** [comment]
Yes, that seems reasonable. I am a bit swamped at work right now, but I will happily take a look at this on not too long. :-)
