### ISSUE TITLE
Print values of the stdout and stderr in shell

### ISSUE THREAD

**Issue by juusechec** [lambdaisland/kaocha#428]
Hi all and thanks for your work. I'm using kaocha runner in this way:
```clj
(kaocha.runner/exec-fn {
     :tests           [{:skip       [...]
                        :test-paths [...]}]
}))
```
Everything executes well, but when I have an error in the projects that I am testing, It's difficult to see because the stdout is hidden. What is the parameter to show all messages printed to stdout?

**Comment by plexus** [comment]
Please make minimal effort to read the documentation, or ask the community in Slack. This is a place to report bugs and issues, not a support channel. Note that exec-fn is community contributed, we don't make any attempt to offer support for it. If you want to invoke kaocha programmatically use `kaocha.repl` or `kaocha.api`.

You can try `--print-config` to see what the correct name of the configuration flag is, but I can't guarantee it'll get passed down when using exec-fn.

**Comment by juusechec** [comment]
👋 Thank you.
If anyone is looking for a solution in the future:
```diff
(kaocha.runner/exec-fn {
     :tests           [{:skip       [...]
                        :test-paths [...]}]
+    :capture-output? false                   
}))
```
