### ISSUE TITLE
Homepage of GitHub repository links to outdated documentation

### ISSUE THREAD

**Issue by devurandom** [lambdaisland/kaocha#439]
The homepage of this repository links to https://cljdoc.org/d/lambdaisland/kaocha/1.0.861/doc/1-introduction which is outdated. It could instead link to https://cljdoc.org/d/lambdaisland/kaocha/ which redirects to the latest documentation.

![image](https://github.com/lambdaisland/kaocha/assets/63082/a1d367f1-2a6a-4422-af60-bab6778141bd)

**Comment by oxalorg** [comment]
Thanks, made the change!
