### ISSUE TITLE
Add the notifier plugin to the main code base

### ISSUE THREAD

**Issue by plexus** [lambdaisland/kaocha#44]
Ryan McCuaig (@rgm) wrote a hook to call the system notifier when a test run passes or fails. I cleaned it up a bit to use some helper functions from `kaocha.result`, and coverted it into a plugin:

https://gist.github.com/plexus/e5befecc5b3f950d67944dd63401c580

Ryan agreed to add this to the main code base, which I think would be great, as this is generally quite useful, and doesn't require pulling in extra dependencies.

https://clojurians-log.clojureverse.org/kaocha/2019-01-19

Todo

- [x] Copy this over to `src/kaocha/plugin/notifier.clj`, and update the namespace and plugin name accordingly
- [x] Make the command configurable (current logic to find a command can still be used as a default, set in a `config` hook)
- [x] Add a feature test so that it becomes part of the documentation

Configuration:

(tip: have a look at the shellwords function in `kaocha_integration.clj` and maybe pull it out somewhere, as it'll be useful to parse the configured command)

```
#kaocha/v1
{:plugins [:kaocha.plugin/notifications]
 :kaocha.plugin.notifications/command "my-notifier %{title} %{message}"}
```

**Comment by rgm** [comment]
I ended up adding a “silent” no-op to the gist version (not yet pushed up) so I didn’t have to swap in a new `tests.edn` for CI. It’s for when no notifier gets detected within `exists?`.

Seem a reasonable way to handle that case? Open to ideas.
