### ISSUE TITLE
defmethod watch! :beholder + wait-and-rescan! currently broken

### ISSUE THREAD

**Issue by ivarref** [lambdaisland/kaocha#440]
Hi, and thanks for a great and useful project!

I noticed that adding `:kaocha.watch/ignore ["*.tmp"]` in `tests.edn` did not work as intended. As far as I can see there are two reasons for that:

`*.tmp` will only match files in the current directory.

`beholder` returns fully qualified names (on both mac and linux).

thus:

```clojure
(glob? (.toPath (java.io.File. "/foo/bar/demo.tmp")) ["*.tmp"])
=> nil
```

I suggest to update the documentation to give `**.tmp` as an example. That will match `/foo/bar/demo.tmp` as well.

The second reason is that `beholder` will return `java.nio.file.Path` and not `java.io.File`which `wait-and-rescan!` expects. This will lead to a NullPointerException.

I have written a pull request that fixes this.

Thanks again for a great project!
Kind regards
Ivar

**Comment by plexus** [comment]
Thanks! This might be because we switched at some point from another watcher lib to beholder. Glad it's fixed!
