### ISSUE TITLE
Don't print unrelated output with failing test

### ISSUE THREAD

**Issue by cjohansen** [lambdaisland/kaocha#49]
Currently Kaocha captures output and only prints it in case of failing tests. However, all the output is printed in one block, making it very hard to discern what output originated from which test. It would be nice if captured output was printed back grouped by the test that generated the output.

**Comment by cjohansen** [comment]
Interesting. It's not what I'm seeing. If I place a `prn` in the implementation called by multiple tests, I see this:

<img width="624" alt="image" src="https://user-images.githubusercontent.com/32871/51670192-67626c80-1fc6-11e9-8895-53055477e661.png">

This is the same `deftest`, but each `clojure.test/testing` should only have one line of output, yet it's all grouped under `"Does not trip on circular dependencies"` (which is one `testing`).

**Comment by plexus** [comment]
Right, the inside of a `deftest` are opaque to Kaocha, for Kaocha 1 deftest = 1 test.

**Comment by cjohansen** [comment]
Ah, I see. My bad then, sorry!

**Comment by plexus** [comment]
No worries, thanks for using Kaocha!

**Comment by cjohansen** [comment]
Thanks for making it :)
