### ISSUE TITLE
Add .gitignore support to --watch

### ISSUE THREAD

**Issue by plexus** [lambdaisland/kaocha#55]
With #54 --watch has gained the ability to ignore certain files based on glob-like patterns. The patterns are those provided by the Java [PatchMatcher](https://docs.oracle.com/javase/7/docs/api/java/nio/file/FileSystem.html#getPathMatcher(java.lang.String)) API.

It would be useful to use any patterns set in `.gitignore` as a default, but the `.gitignore` file format is quite particular and so we need to implement a parser that converts it to Java's glob patterns.

For reference:

- [Format description](https://www.kernel.org/pub/software/scm/git/docs/gitignore.html#_pattern_format)
- [implementation in Go](https://github.com/zabawaba99/go-gitignore/blob/master/ignore.go)
- [implementation in JS](https://github.com/Floobits/js-git-ignore/blob/master/lib/ignore.js)
- [implementation in Rust](https://docs.rs/crate/gitignore/1.0.6/source/src/pattern.rs)

**Comment by danielcompton** [comment]
Another option would be to use git ls-files (https://git-scm.com/docs/git-ls-files). Then you would only need to parse a more straightforward list of files, but more care would be needed in invalidating the list. One other thing to remember which I didn’t see at first glance in some of the code is that you need to look for gitignores up and down the tree

**Comment by alysbrooks** [comment]
In theory, we could make this broader than `.gitignore`. I don't want to add extra syntaxes to the original implementation, but we can get support for other ignores almost for free.

* Ripgrep (rg) and the Silver Searcher (Ag) use `.ignore` files, which I think uses the same syntax.
* I think Mercurial ignore files with `syntax: glob` use a very similar syntax, but I'm not sure it's the same.

That being said, we don't want to use ignore files indiscriminately. It's very plausible someone would put their tests directory in `.dockerignore`, for example.

**Comment by alysbrooks** [comment]
This was closed by #189.
