### ISSUE TITLE
A request for tips and tricks for extending kaocha

### ISSUE THREAD

**Issue by magnars** [lambdaisland/kaocha#56]
Hi! I am about to start work on my first kaocha plugin. When sitting down I found myself at a bit of a loss - wondering how to tackle the issue.

Do you have a preferred workflow when adding a new plugin? How do you test it in the repl? What's a good way to get a quick feedback cycle? Do you write tests for the plugin with kaocha? How do you avoid the plugin itself interfering with its tests?

I would be happy for just a few pointers in the right direction. Don't feel obligated to write an essay on the topic. :-)

**Comment by magnars** [comment]
Hi Arne. Thank you so much, this seems like a good starting point. I'm glad you suggested a way to develop in the repl.

I am writing the plugin to switch actual and expected in `(is (= ...))` forms, so I will be using the new pre-report hook. I didn't include that information to begin with because I thought maybe your answer could be usefully added to [this page](https://cljdoc.org/d/lambdaisland/kaocha/0.0-367/doc/8-extending). :)

**Comment by plexus** [comment]
I agree :) I figured I'd do a brain dump here first, then see how to work it into the docs afterwards.

For this particular case I would probably do something like this: write a simple test with a single assertion, and in your `pre-report` hook store all events you get into an atom.

```
(def events (atom []))
(defplugin ...
  (pre-report [e] (swap! events conj e)))
```

Then find the one that has a type of `:fail`, and then run that one through your hook and then through `kaocha.report/print-expr`.

``` clojure
(def fail (first (filter #(= (:type %) :fail) @events)))

(kaocha.report/print-expr (plugin-pre-report-hook fail))
```

**Comment by plexus** [comment]
This is now part of the docs on extending.

**Comment by magnars** [comment]
Thanks for your help with this. The plugin is now released. :) https://github.com/magnars/kaocha-noyoda
