### ISSUE TITLE
Cucumber and Clojurescript

### ISSUE THREAD

**Issue by Wolfgang51** [lambdaisland/kaocha#73]
Hey there, 

First off, I really love what you are doing here with this library 😊. I particularly like how it bridges Clojure and Clojure(script) testing into one framework. With that being said, have you considered creating a Clojure(script) implementation of Cucumber? This seems to be a pain point for the Clojure(script) community especially with those utilizing Reagent and Re-frame.

**Comment by plexus** [comment]
Hi @Wolfgang51 , maintaining the JVM version of kaocha-cucumber has already proven to be a huge pain, even in it's short lifespan. Given that I no longer have funding to work on Kaocha I do not plan to add more test types myself, at least not in the short term.

I do have some clients interested in figuring out a good story around browser-based integration testing, so there might be stuff happening there, but it will almost certainly not be JavaScript cucumber based.

**Comment by AndreaCrotti** [comment]
Not sure if it helps but we have this library @Wolfgang51 
https://github.com/FundingCircle/jukebox/
(which however is not CLJS compatible atm, but maybe it could be if there is enough interest)

**Comment by plexus** [comment]
If you're specifically looking for browser UI testing (what people in the Ruby space use Cucumber+Capybara for) then I would look into https://github.com/igrishaev/etaoin

**Comment by plexus** [comment]
Closing as "wontfix"
