### ISSUE TITLE
Slightly confusing output

### ISSUE THREAD

**Issue by AndreaCrotti** [lambdaisland/kaocha#80]
I was a bit confused by the test output, since `-2` is also a number so I wasn't sure for a moment what was the actual result, `-2` or `+1`.
![Screen Shot 2019-03-14 at 11 02 43](https://user-images.githubusercontent.com/53640/54352104-c482b200-4648-11e9-9577-3929a6ff91de.png)

Maybe instead of just expected and actual we also just need a Diff row?

**Comment by hukka** [comment]
Not having the untouched actual results also makes it more difficult to copy, paste, manipulate and analyze more complicated data structures.

**Comment by alysbrooks** [comment]
We now have the `--diff-style :none` option, so you can turn it off. We could do more tweaking, probably, but I think this is a good solution. What do you think @AndreaCrotti and @hukka?

**Comment by AndreaCrotti** [comment]
yeah tbh the problem for  me was really only when you have just a number as output, which doesn't happen that often anyway.
So feel free to close the issue imho.

**Comment by alysbrooks** [comment]
If more people encounter this, we can reopen, but I think we're safe to close it.
