### ISSUE TITLE
--watch hangs if inotify resources are exhausted

### ISSUE THREAD

**Issue by davesann** [lambdaisland/kaocha#88]
I am adding this issue in case anyone else has the same problem. It took a couple of hours to figure out. Applies to linux systems.

I was testing Kaocha and found that using the --watch option hung with no output. Without it, tests would run ok.

Cause:  inotify resources were exhausted. 
Culprit: probably atom. So if you use it, you may see the same issue.

If you see the symptom, check with "tail -f some-file" and you will see this in the output:
```
tail: inotify resources exhausted
tail: inotify cannot be used, reverting to polling
```

You can increase available resources - refer here: https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers

**Comment by davesann** [comment]
solution provided in issue - raised for documentation purposes.

**Comment by plexus** [comment]
Wow, good to know!
