### ISSUE TITLE
0 test vars, 0 assertions, 0 failures

### ISSUE THREAD

**Issue by vemv** [lambdaisland/kaocha#9]
Hey there,

library looking neat. Kudos.

I'm having trouble getting to run it:

* My ~/.lein/profiles.clj:

```
{:user {dependencies [[lambdaisland/kaocha "0.0-189" :exclusions [org.clojure/clojure]]]
...
```

* My tests.edn:

```
{:tests [{:id :unit
          :test-paths ["test"] ; Correct one
          :source-paths ["src" "and-other-stuff"]}] ; Correct values
 }
```

I/O:

```
$ lein run -m kaocha.runner unit --fail-fast
Randomized with --seed 798394175
[]
0 test vars, 0 assertions, 0 failures
```

A number of tests should be run instead. How to debug this?

Cheers - Victor

**Comment by plexus** [comment]
Hi Victor,

Do your test namespaces end in "-test"? If not you need to change the
namespace pattern in the configuration.

**Comment by vemv** [comment]
That was it, thanks!

Having  to specify a pattern was somewhat unexpected, so perhaps this need can be compensated with a warning message:

```
0 test vars, 0 assertions, 0 failures
If this is anomalous, please refer to the Configuration section.
```
