### ISSUE TITLE
--watch hangs with tools.deps, but `:watch? true` works

### ISSUE THREAD

**Issue by WhittlesJr** [lambdaisland/kaocha#93]
Other command-line switches seem to work, and the watch mode does work when configured in tests.edn. 

Again, I'm using tools.deps instead of lein. Also, I'm on Linux (NixOS). 

I've looked at https://github.com/lambdaisland/kaocha/issues/88, and I'm pretty sure my inotify resources are not exhausted.

**Comment by WhittlesJr** [comment]
Interestingly, it is the mere *presence* of the tests.edn file that makes the difference. Even if it's totally blank, and you use the CLI `--watch` option, it succeeds. But take the file away, and it hangs. I found where it hangs specifically:

https://github.com/lambdaisland/kaocha/blob/dca442b2fd57a4f46e333b7549087bddc0a8e0b2/src/kaocha/watch.clj#L204

**Comment by WhittlesJr** [comment]
Er, not quite, it's even weirder. With an empty tests.edn, and the --watch flag on, it does proceed to run your suites, and it will re-run if you it enter in the terminal, but it doesn't actually watch for changes. If you change and save a file, it does not re-run.

BUT, with:
```
#kaocha/v1
{:watch? true}
```
for your tests.edn, it works as expected.

**Comment by WhittlesJr** [comment]
Nice, thank you!

**Comment by WhittlesJr** [comment]
I think this needs to be re-opened. It has some unit test failures, and when I try to run --watch with no tests.edn, I get:
``
java.nio.file.NoSuchFileException: /home/alexj/Documents/Repositories/clj-canopen/tests.edn                                                                                    
 at sun.nio.fs.UnixException.translateToIOException (UnixException.java:86)
    sun.nio.fs.UnixException.asIOException (UnixException.java:111)
    sun.nio.fs.LinuxWatchService$Poller.implRegister (LinuxWatchService.java:246)
    sun.nio.fs.AbstractPoller.processRequests (AbstractPoller.java:260)
    sun.nio.fs.LinuxWatchService$Poller.run (LinuxWatchService.java:364)
    java.lang.Thread.run (Thread.java:748)
[watch] watching stopped.
```

**Comment by plexus** [comment]
Alright, I spoke too soon. Let me check this.

**Comment by plexus** [comment]
Fixed!
