### ISSUE TITLE
How do you use watch from the REPL?

### ISSUE THREAD

**Issue by kanwei** [lambdaisland/kaocha#97]
I have a ```dev``` namespace I use to start various runners, like shadow-cljs, SCSS building, etc. I'm now trying to also start kaocha watch:

```
[kaocha.watch :as kao-watch]
[kaocha.repl :as kao-repl]
```

However, adding
```(kao-watch/run (kao-repl/config))``` to the dev file doesn't seem to do anything - nothing runs when test files are changed. ```(kao-repl/run-all)``` runs all the tests, so it seems to be just the watcher. Any ideas?

**Comment by JJ-Atkinson** [comment]
That command works fine for me on the newest version of kaocha.
